#!/bin/bash

echo "作者是Linux新手，请严格审核自己输入的内容，避免出错"
echo ""
echo "操作列表："
echo "1. 安装SSR"
echo "2. 安装SeVPN"
echo "3. 安装BBR加速"
echo "4. 安装tinyproxy"
echo "5. 放行端口"
echo "6. 查询端口运行状态"
echo ""
echo "请选择您需要的操作，若不输入则退出："
read comd
if [[ $comd == 1 ]]; then
	echo "您已选择第1项，按任意键继续，或按Ctrl+C退出"
	read
	wget https://github.com/RosallaFie/enweb/raw/master/shadowsocksr.tar.gz
	chmod 777 ./shadowsocksr.tar.gz
	tar zxf ./shadowsocksr.tar.gz
	bash ml
elif [[ $comd == 2 ]]; then
	echo "您已选择第2项，按任意键继续，或按Ctrl+C退出"
	read
	wget https://github.com/RosallaFie/enweb/raw/master/sevpn
	chmod 777 ./sevpn
	bash sevpn
elif [[ $comd == 3 ]]; then
	echo "您已选择第3项，按任意键继续，或按Ctrl+C退出"
	read
	wget --no-check-certificate https://github.com/teddysun/across/raw/master/bbr.sh
	chmod +x bbr.sh
	./bbr.sh
elif [[ $comd == 4 ]]; then
	echo "您已选择第4项，按任意键继续，或按Ctrl+C退出"
	read
	cd /root
	wget https://github.com/RosallaFie/enweb/raw/master/tinyproxyX64.zip
	unzip tinyproxyX64.zip
	chmod 777 ./tinyproxy
	echo "是否设置开机自启?"
	echo "输入1表示确定"
	echo "输入其它或不输入表示不启用开机自启"
	read onstartup
	if [[ $onstartup == 1 ]]; then
		echo "/root/tinyproxy -c /root/tinyproxy.conf">>/etc/rc.local
		echo "已设置开机自启"
	else
		echo "已选择不设置开机自启"
	fi
	echo "配置文件在/root/tinyproxy.conf"
	echo "默认端口为:5050，默认验证头为：Hello"
elif [[ $comd == 5 ]]; then
	echo "您已选择第5项，按任意键继续，或按Ctrl+C退出"
	read
	echo "请输入端口："
	read theport
	echo "已选择端口：$theport"
	iptables -I INPUT -p tcp --dport $theport -j ACCEPT
	service iptables save
	service iptables restart
elif [[ $comd == 6 ]]; then
	netstat -antp
else
	echo "程序退出"
	exit 0
fi
